// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvCgB_zdusGiFsr5bILJZYR2ZYTI1XJU',
    appId: '1:225137332601:web:5c1f0f0a6f5c9ae2c01fa8',
    messagingSenderId: '225137332601',
    projectId: 'nakila-73d34',
    authDomain: 'nakila-73d34.firebaseapp.com',
    storageBucket: 'nakila-73d34.firebasestorage.app',
    measurementId: 'G-Z11S2BVKS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8sRpGO6Vg12zf_FjbiYHlGJjbNob5apQ',
    appId: '1:225137332601:android:245fbc29ca07fcb4c01fa8',
    messagingSenderId: '225137332601',
    projectId: 'nakila-73d34',
    storageBucket: 'nakila-73d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9jDKPxAhWOE6mpZ55N8j8Qzr_Gw81FmQ',
    appId: '1:225137332601:ios:6655442f639aeca2c01fa8',
    messagingSenderId: '225137332601',
    projectId: 'nakila-73d34',
    storageBucket: 'nakila-73d34.firebasestorage.app',
    iosBundleId: 'com.example.nakila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9jDKPxAhWOE6mpZ55N8j8Qzr_Gw81FmQ',
    appId: '1:225137332601:ios:6655442f639aeca2c01fa8',
    messagingSenderId: '225137332601',
    projectId: 'nakila-73d34',
    storageBucket: 'nakila-73d34.firebasestorage.app',
    iosBundleId: 'com.example.nakila',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUvCgB_zdusGiFsr5bILJZYR2ZYTI1XJU',
    appId: '1:225137332601:web:e340b67f4210673cc01fa8',
    messagingSenderId: '225137332601',
    projectId: 'nakila-73d34',
    authDomain: 'nakila-73d34.firebaseapp.com',
    storageBucket: 'nakila-73d34.firebasestorage.app',
    measurementId: 'G-T5FKPHHE8N',
  );
}